extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  batch:
    timeout: 1s

exporters:
  debug:
    verbosity: detailed
  otlphttp/tempo:
    compression: gzip
    encoding: proto
    endpoint: http://tempo:4318
    sending_queue:
      enabled: true
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 10s
      max_elapsed_time: 30s
  otlphttp/victoriametrics:
    compression: gzip
    encoding: proto
    metrics_endpoint: http://victoriametrics:8428/opentelemetry/v1/metrics
    sending_queue:
      enabled: true
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 10s
      max_elapsed_time: 30s
  otlphttp/loki:
    compression: gzip
    encoding: proto
    endpoint: http://loki:3100/otlp
    sending_queue:
      enabled: true
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 10s
      max_elapsed_time: 30s

service:
  extensions: [health_check]
  telemetry:
    resource:
      attributes:
        - name: service.name
          value: geordi-otel-collector
        - name: service.namespace
          value: geordi
        - name: deployment.environment.name
          value: development
        - name: geordi.telemetry.origin
          value: platform
        - name: geordi.platform.component
          value: otel-collector
    logs:
      level: INFO
      encoding: json
    metrics:
      level: normal
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
                without_units: true
                without_type_suffix: true
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/victoriametrics]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/loki]
